# EN.580.637 Homework

Author: Kuai Yu, Ruitao Hu, Langxin Yang

Goal: The goal of the project will be to write a piece of software (possible languages are
Python, Julia, and MATLAB), that matches N patients with K doctors. Each patient is allowed to
provide a ranked list of their preference for doctors, however doctors are prohibited from
displaying preferences for patients. Thus the code should takes in the following:

● A list of ranked preferences, 1 list for each patient

● A maximum capacity for each doctor (can initially assume the same capacity - note the
total capacity should exceed the number of patients
And the code should return:

● A list of assignments indicating which doctors are to take care of which patients

Details: For this assignment please work in groups of at most 3 individuals. Teams can choose
to implement a classical algorithm, such as the Hungarian algorithm, however other algorithms
are also acceptable, including any of a number of auction or transport optimization algorithms in
the literature. The code should be include:

1. A Github repository housing all the code synced amongst the group
2. Commented and documented code, including references and an explanation of the
algorithm implemented
3. A functioning demo script (can be a jupytr notebook)

## Import Packages

In [36]:
import numpy as np

## Load Example

Here is a example:
* Assuming each patient has a unqiue preference to each doctor
* doctors_capacity indicates each doctor's max capacity for patients
* preference contains each patient's preference for doctor
* rank from 0-3 high to low i.e. 0 is the max preference, len(doctors_capacity)-1 is the least preference

1. Exmaple 1

In [37]:
doctors_capacity = [2, 3, 1, 5]
doc_name2id = {0: "A", 1: "B", 2: "C", 3: "D"}
#rank from 0-3 high to low
preference = np.array([[0, 1, 2, 3], [0, 3, 1, 2], [1, 3, 2, 0], [3, 1, 0, 2], [3, 2, 0, 1]])
num_patient = preference.shape[0]
print(preference)
print(num_patient)

[[0 1 2 3]
 [0 3 1 2]
 [1 3 2 0]
 [3 1 0 2]
 [3 2 0 1]]
5


2. Example 2

In [38]:
doctors_capacity_2 = [2, 3, 1, 5, 1, 2, 2]
doc_name2id_2 = {0: "A", 1: "B", 2: "C", 3: "D", 4: "E", 5: "F", 6: "G"}
#rank from 0-3 high to low
preference_2 = np.array([[0, 1, 2, 3, 4, 5, 6], 
                         [0, 3, 1, 2, 6, 4, 5], 
                         [4, 6, 5, 1, 3, 2, 0], 
                         [3, 1, 5, 4, 6, 0, 2], 
                         [3, 2, 0, 4, 5, 6, 1],
                         [6, 5, 4, 3, 2, 1, 0]])
num_patient_2 = preference_2.shape[0]
print(preference_2 + 1)


[[1 2 3 4 5 6 7]
 [1 4 2 3 7 5 6]
 [5 7 6 2 4 3 1]
 [4 2 6 5 7 1 3]
 [4 3 1 5 6 7 2]
 [7 6 5 4 3 2 1]]


## Print preference

In [39]:
for i in range(len(preference)):
    pref_each = preference[i]
    pref_name = []
    for j in pref_each:
        pref_name.append(doc_name2id.get(j))
    pref_name_list = '>'.join(pref_name)
    print("For patient %d, his or her preference is %s" % (i, pref_name_list))

For patient 0, his or her preference is A>B>C>D
For patient 1, his or her preference is A>D>B>C
For patient 2, his or her preference is B>D>C>A
For patient 3, his or her preference is D>B>A>C
For patient 4, his or her preference is D>C>A>B


# Run Demo

## replicate columns by doctors' capacities

Our program uses hungarian algorithm to achieve matching. One issue that Hungarian algorithm could not achieve is that it could not handle multiple capacity. In order to fix this issue, we multiple the columns with each corresponding capacity. For instance, if a doctor has 4 capacity, we make him 4 columns. This is coded as function `load_preference`.

* Here we will run Hungarian algorithm coded in the HungarianAlgorithm.py

In [40]:
from HungarianAlgorithm import *

In [41]:
help(load_preference)

Help on function load_preference in module HungarianAlgorithm:

load_preference(preference_before, doctors_capacity)
    Replicate columns in matrix according to different doctors_capacity, and pad matrix with max value to achieve
    a square matrix
    
    :param doctors_capacity:
    :param preference: a numpy matrix
    :return: a modified matrix



1. example 1

In [42]:
preference = load_preference(preference, doctors_capacity)
print(preference)

[[0 0 1 1 1 2 3 3 3 3 3]
 [0 0 3 3 3 1 2 2 2 2 2]
 [1 1 3 3 3 2 0 0 0 0 0]
 [3 3 1 1 1 0 2 2 2 2 2]
 [3 3 2 2 2 0 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3]]


2. example 2

In [43]:
preference_2 = load_preference(preference_2, doctors_capacity_2)
print(preference_2)

[[0 0 1 1 1 2 3 3 3 3 3 4 5 5 6 6]
 [0 0 3 3 3 1 2 2 2 2 2 6 4 4 5 5]
 [4 4 6 6 6 5 1 1 1 1 1 3 2 2 0 0]
 [3 3 1 1 1 5 4 4 4 4 4 6 0 0 2 2]
 [3 3 2 2 2 0 4 4 4 4 4 5 6 6 1 1]
 [6 6 5 5 5 4 3 3 3 3 3 2 1 1 0 0]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]]


## Run Hungarian algorithm

We use `hungarian_algorithm` to run the linear assignment

In [44]:
help(hungarian_algorithm)

Help on function hungarian_algorithm in module HungarianAlgorithm:

hungarian_algorithm(matrix)
    Return the result of linear assignment from matrix using hungarian algorithm
    
    :param matrix: a numpy matrix
    :return: indices that optimizes the the linear assignment problem



1. example 1

In [53]:
result = hungarian_algorithm(preference)
result

[(0, 0),
 (1, 1),
 (3, 2),
 (2, 6),
 (4, 5),
 (5, 3),
 (6, 4),
 (7, 7),
 (8, 8),
 (9, 9),
 (10, 10)]

* Use transform_result to remove additional padding

In [54]:
help(transform_result)

Help on function transform_result in module HungarianAlgorithm:

transform_result(result, doctors_capacity, doc_name2id, num_patient)
    Transform result into a dictionary(patient: doctor) and remove padding value
    :param result: result matrix from Hungarian algorithm
    :param doctors_capacity: dictionary contains doctor capacity
    :param doc_name2id: dictionary contains name to doctor index
    :param num_patient: number of patients
    :return: a dictionary(patient: doctor)



In [47]:
final_result = transform_result(result, doctors_capacity, doc_name2id, num_patient)

In [48]:
final_result

{0: 'A', 1: 'A', 2: 'D', 3: 'B', 4: 'C'}

2. example 2

In [49]:
result_2 = hungarian_algorithm(preference_2)
final_result_2 = transform_result(result_2, doctors_capacity_2, doc_name2id_2, num_patient_2)
final_result_2

{0: 'A', 1: 'A', 2: 'G', 3: 'F', 4: 'C', 5: 'G'}

## Print Result

* Here we display the result of our program

1. example 1

In [50]:
for patient_idx in final_result.keys():  
    print("patient {} is taken care by doctor {}".format(str(patient_idx), final_result[patient_idx]))
       

patient 0 is taken care by doctor A
patient 1 is taken care by doctor A
patient 2 is taken care by doctor D
patient 3 is taken care by doctor B
patient 4 is taken care by doctor C


In [51]:
doctors_to_patients = {}
for patient in final_result.keys():
    doctor = final_result[patient]
    if doctor not in doctors_to_patients.keys():
        doctors_to_patients[doctor] = []
    doctors_to_patients[doctor].append(patient)

for doctor in doctors_to_patients.keys():
    print("doctor {} takes care of patients {}".format(doctor, str(doctors_to_patients[doctor])))

doctor A takes care of patients [0, 1]
doctor D takes care of patients [2]
doctor B takes care of patients [3]
doctor C takes care of patients [4]


2. example 2

In [52]:
for patient_idx in final_result_2.keys():  
    print("patient {} is taken care by doctor {}".format(str(patient_idx), final_result_2[patient_idx]))
doctors_to_patients_2 = {}
for patient in final_result_2.keys():
    doctor = final_result_2[patient]
    if doctor not in doctors_to_patients_2.keys():
        doctors_to_patients_2[doctor] = []
    doctors_to_patients_2[doctor].append(patient)

for doctor in doctors_to_patients_2.keys():
    print("doctor {} takes care of patients {}".format(doctor, str(doctors_to_patients_2[doctor])))

patient 0 is taken care by doctor A
patient 1 is taken care by doctor A
patient 2 is taken care by doctor G
patient 3 is taken care by doctor F
patient 4 is taken care by doctor C
patient 5 is taken care by doctor G
doctor A takes care of patients [0, 1]
doctor G takes care of patients [2, 5]
doctor F takes care of patients [3]
doctor C takes care of patients [4]


# Reference

Eason, E. 2021. Hungarian algorithm Introduction &amp; Python implementation. Medium. https://python.plainenglish.io/hungarian-algorithm-introduction-python-implementation-93e7c0890e15 

Kuhn, H.W., 1955. The Hungarian method for the assignment problem. Naval Research Logistics Quarterly 2, 83–97.. doi:10.1002/nav.3800020109

Harris, C.R., Millman, K.J., van der Walt, S.J. et al. 2020. Array programming with NumPy. Nature 585, 357–362 . 
doi: 10.1038/s41586-020-2649-2. (Publisher link).
