# EN.580.637 Homework

Goal: The goal of the project will be to write a piece of software (possible languages are
Python, Julia, and MATLAB), that matches N patients with K doctors. Each patient is allowed to
provide a ranked list of their preference for doctors, however doctors are prohibited from
displaying preferences for patients. Thus the code should takes in the following:

● A list of ranked preferences, 1 list for each patient

● A maximum capacity for each doctor (can initially assume the same capacity - note the
total capacity should exceed the number of patients
And the code should return:

● A list of assignments indicating which doctors are to take care of which patients

Details: For this assignment please work in groups of at most 3 individuals. Teams can choose
to implement a classical algorithm, such as the Hungarian algorithm, however other algorithms
are also acceptable, including any of a number of auction or transport optimization algorithms in
the literature. The code should be include:

1. A Github repository housing all the code synced amongst the group
2. Commented and documented code, including references and an explanation of the
algorithm implemented
3. A functioning demo script (can be a jupytr notebook)

## Import Packages

In [2]:
import numpy as np
from scipy.optimize import linear_sum_assignment

## Load Example

In [3]:
doctors_capacity = [2, 3, 1, 5]
preference = np.array([[0, 1, 2, 3], [0, 3, 1, 2], [1, 3, 2, 0], [3, 1, 0, 2], [3, 2, 0, 1]])
print(preference)

[[0 1 2 3]
 [0 3 1 2]
 [1 3 2 0]
 [3 1 0 2]
 [3 2 0 1]]


## replicate columns by doctors' capacities

In [13]:
hungarian_matrix = preference[:, 0]
cur_index = 0
for i in range(len(doctors_capacity)):
    capacity = doctors_capacity[i]
    preference = np.insert(preference, 
                           (capacity - 1) * [cur_index], 
                           preference[:, [cur_index]],
                           axis=1)
    cur_index += capacity


In [14]:
print(preference)

[[0 0 1 1 1 2 3 3 3 3 3]
 [0 0 3 3 3 1 2 2 2 2 2]
 [1 1 3 3 3 2 0 0 0 0 0]
 [3 3 1 1 1 0 2 2 2 2 2]
 [3 3 2 2 2 0 1 1 1 1 1]]


## Run Hungarian algorithm

In [15]:
row_ind, col_ind = linear_sum_assignment(preference)
print(row_ind)
print(col_ind)

[0 1 2 3 4]
[0 1 6 2 5]


In [12]:
doctors_range = [sum(doctors_capacity[: i]) for i in range(1, len(doctors_capacity) + 1)]
print(doctors_range)

[2, 5, 6, 11]


## Print Result

In [23]:
for patient_idx in range(len(col_ind)):
    doctor_idx = col_ind[patient_idx]
    j = 0
    while j < len(doctors_range) and doctor_idx >= doctors_range[j]:
        j+=1
    print("patient {} is taken care by doctor {}".format(str(patient_idx), str(j)))
        

patient 0 is taken care by doctor 0
patient 1 is taken care by doctor 0
patient 2 is taken care by doctor 3
patient 3 is taken care by doctor 1
patient 4 is taken care by doctor 2


In [20]:
str(0)

'0'